[2021-10-07 00:00:07,127] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Not_Accurate 2021-10-06T00:00:00+00:00 [queued]>
[2021-10-07 00:00:07,171] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Not_Accurate 2021-10-06T00:00:00+00:00 [queued]>
[2021-10-07 00:00:07,173] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-07 00:00:07,175] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-07 00:00:07,176] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-07 00:00:07,198] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): Not_Accurate> on 2021-10-06T00:00:00+00:00
[2021-10-07 00:00:07,210] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Not_Accurate', '2021-10-06T00:00:00+00:00', '--job-id', '157', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpdvmmh4cw', '--error-file', '/tmp/tmpl42yr549']
[2021-10-07 00:00:07,205] {standard_task_runner.py:52} INFO - Started process 68028 to run task
[2021-10-07 00:00:07,213] {standard_task_runner.py:77} INFO - Job 157: Subtask Not_Accurate
[2021-10-07 00:00:07,295] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Not_Accurate 2021-10-06T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-07 00:00:07,400] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Not_Accurate
AIRFLOW_CTX_EXECUTION_DATE=2021-10-06T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-06T00:00:00+00:00
[2021-10-07 00:00:07,405] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-10-07 00:00:07,408] {subprocess.py:63} INFO - Running command: ['bash', '-c', "printf '============\n\nNot Accurate\n\n=============' "]
[2021-10-07 00:00:07,422] {subprocess.py:74} INFO - Output:
[2021-10-07 00:00:07,439] {subprocess.py:78} INFO - ============
[2021-10-07 00:00:07,441] {subprocess.py:78} INFO - 
[2021-10-07 00:00:07,442] {subprocess.py:78} INFO - Not Accurate
[2021-10-07 00:00:07,442] {subprocess.py:78} INFO - 
[2021-10-07 00:00:07,443] {subprocess.py:78} INFO - =============
[2021-10-07 00:00:07,444] {subprocess.py:82} INFO - Command exited with return code 0
[2021-10-07 00:00:07,489] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Not_Accurate, execution_date=20211006T000000, start_date=20211007T000007, end_date=20211007T000007
[2021-10-07 00:00:07,556] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-07 00:00:07,590] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
