[2021-10-09 00:00:03,562] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Not_Accurate 2021-10-08T00:00:00+00:00 [queued]>
[2021-10-09 00:00:03,586] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Not_Accurate 2021-10-08T00:00:00+00:00 [queued]>
[2021-10-09 00:00:03,587] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-09 00:00:03,588] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-09 00:00:03,589] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-09 00:00:03,602] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): Not_Accurate> on 2021-10-08T00:00:00+00:00
[2021-10-09 00:00:03,615] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Not_Accurate', '2021-10-08T00:00:00+00:00', '--job-id', '167', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpcwaiufn6', '--error-file', '/tmp/tmpj2mjct1g']
[2021-10-09 00:00:03,608] {standard_task_runner.py:52} INFO - Started process 56722 to run task
[2021-10-09 00:00:03,617] {standard_task_runner.py:77} INFO - Job 167: Subtask Not_Accurate
[2021-10-09 00:00:03,683] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Not_Accurate 2021-10-08T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-09 00:00:03,751] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Not_Accurate
AIRFLOW_CTX_EXECUTION_DATE=2021-10-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-08T00:00:00+00:00
[2021-10-09 00:00:03,754] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-10-09 00:00:03,758] {subprocess.py:63} INFO - Running command: ['bash', '-c', "printf '============\n\nNot Accurate\n\n=============' "]
[2021-10-09 00:00:03,772] {subprocess.py:74} INFO - Output:
[2021-10-09 00:00:03,773] {subprocess.py:78} INFO - ============
[2021-10-09 00:00:03,775] {subprocess.py:78} INFO - 
[2021-10-09 00:00:03,776] {subprocess.py:78} INFO - Not Accurate
[2021-10-09 00:00:03,777] {subprocess.py:78} INFO - 
[2021-10-09 00:00:03,778] {subprocess.py:78} INFO - =============
[2021-10-09 00:00:03,779] {subprocess.py:82} INFO - Command exited with return code 0
[2021-10-09 00:00:03,811] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Not_Accurate, execution_date=20211008T000000, start_date=20211009T000003, end_date=20211009T000003
[2021-10-09 00:00:03,877] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-09 00:00:03,905] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
