[2021-10-03 00:37:09,040] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Not_Accurate 2021-10-03T00:37:05.394662+00:00 [queued]>
[2021-10-03 00:37:09,068] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Not_Accurate 2021-10-03T00:37:05.394662+00:00 [queued]>
[2021-10-03 00:37:09,069] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-03 00:37:09,071] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-03 00:37:09,072] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-03 00:37:09,084] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): Not_Accurate> on 2021-10-03T00:37:05.394662+00:00
[2021-10-03 00:37:09,089] {standard_task_runner.py:52} INFO - Started process 24222 to run task
[2021-10-03 00:37:09,094] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Not_Accurate', '2021-10-03T00:37:05.394662+00:00', '--job-id', '62', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpa207sh7h', '--error-file', '/tmp/tmpmq5x5fnp']
[2021-10-03 00:37:09,097] {standard_task_runner.py:77} INFO - Job 62: Subtask Not_Accurate
[2021-10-03 00:37:09,165] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Not_Accurate 2021-10-03T00:37:05.394662+00:00 [running]> on host d6b4131456ad
[2021-10-03 00:37:09,238] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Not_Accurate
AIRFLOW_CTX_EXECUTION_DATE=2021-10-03T00:37:05.394662+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-03T00:37:05.394662+00:00
[2021-10-03 00:37:09,241] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-10-03 00:37:09,243] {subprocess.py:63} INFO - Running command: ['bash', '-c', "echo 'Not Accurate'"]
[2021-10-03 00:37:09,253] {subprocess.py:74} INFO - Output:
[2021-10-03 00:37:09,254] {subprocess.py:78} INFO - Not Accurate
[2021-10-03 00:37:09,256] {subprocess.py:82} INFO - Command exited with return code 0
[2021-10-03 00:37:09,293] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Not_Accurate, execution_date=20211003T003705, start_date=20211003T003709, end_date=20211003T003709
[2021-10-03 00:37:09,359] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-03 00:37:09,394] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
