[2021-10-22 00:00:02,343] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_A 2021-10-21T00:00:00+00:00 [queued]>
[2021-10-22 00:00:02,399] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_A 2021-10-21T00:00:00+00:00 [queued]>
[2021-10-22 00:00:02,400] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-22 00:00:02,403] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-22 00:00:02,412] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-22 00:00:02,436] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): Training_Model_A> on 2021-10-21T00:00:00+00:00
[2021-10-22 00:00:02,441] {standard_task_runner.py:52} INFO - Started process 24776 to run task
[2021-10-22 00:00:02,484] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Training_Model_A', '2021-10-21T00:00:00+00:00', '--job-id', '231', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp0bs95trp', '--error-file', '/tmp/tmppf3kw8e3']
[2021-10-22 00:00:02,488] {standard_task_runner.py:77} INFO - Job 231: Subtask Training_Model_A
[2021-10-22 00:00:02,624] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Training_Model_A 2021-10-21T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-22 00:00:02,767] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Training_Model_A
AIRFLOW_CTX_EXECUTION_DATE=2021-10-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-21T00:00:00+00:00
[2021-10-22 00:00:02,834] {python.py:151} INFO - Done. Returned value was: None
[2021-10-22 00:00:02,872] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Training_Model_A, execution_date=20211021T000000, start_date=20211022T000002, end_date=20211022T000002
[2021-10-22 00:00:02,923] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-22 00:00:02,987] {local_task_job.py:261} INFO - 1 downstream tasks scheduled from follow-on schedule check
