[2021-10-04 02:06:17,586] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_C 2021-10-03T00:00:00+00:00 [queued]>
[2021-10-04 02:06:17,655] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_C 2021-10-03T00:00:00+00:00 [queued]>
[2021-10-04 02:06:17,657] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-04 02:06:17,658] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-04 02:06:17,659] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-04 02:06:17,693] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): Training_Model_C> on 2021-10-03T00:00:00+00:00
[2021-10-04 02:06:17,717] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Training_Model_C', '2021-10-03T00:00:00+00:00', '--job-id', '115', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp1yi082hc', '--error-file', '/tmp/tmpi8cpare9']
[2021-10-04 02:06:17,727] {standard_task_runner.py:77} INFO - Job 115: Subtask Training_Model_C
[2021-10-04 02:06:17,711] {standard_task_runner.py:52} INFO - Started process 32267 to run task
[2021-10-04 02:06:17,899] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Training_Model_C 2021-10-03T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-04 02:06:18,089] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Training_Model_C
AIRFLOW_CTX_EXECUTION_DATE=2021-10-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-03T00:00:00+00:00
[2021-10-04 02:06:18,142] {python.py:151} INFO - Done. Returned value was: None
[2021-10-04 02:06:18,178] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Training_Model_C, execution_date=20211003T000000, start_date=20211004T020617, end_date=20211004T020618
[2021-10-04 02:06:18,262] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-04 02:06:18,326] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
