[2021-10-06 00:00:04,813] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Not_Accurate 2021-10-05T00:00:00+00:00 [queued]>
[2021-10-06 00:00:04,858] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Not_Accurate 2021-10-05T00:00:00+00:00 [queued]>
[2021-10-06 00:00:04,859] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-06 00:00:04,861] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-06 00:00:04,862] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-06 00:00:04,878] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): Not_Accurate> on 2021-10-05T00:00:00+00:00
[2021-10-06 00:00:04,883] {standard_task_runner.py:52} INFO - Started process 15120 to run task
[2021-10-06 00:00:04,889] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Not_Accurate', '2021-10-05T00:00:00+00:00', '--job-id', '152', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpat83x_51', '--error-file', '/tmp/tmpfswi66ee']
[2021-10-06 00:00:04,892] {standard_task_runner.py:77} INFO - Job 152: Subtask Not_Accurate
[2021-10-06 00:00:04,960] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Not_Accurate 2021-10-05T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-06 00:00:05,038] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Not_Accurate
AIRFLOW_CTX_EXECUTION_DATE=2021-10-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-05T00:00:00+00:00
[2021-10-06 00:00:05,041] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-10-06 00:00:05,043] {subprocess.py:63} INFO - Running command: ['bash', '-c', "printf '============\n\nNot Accurate\n\n=============' "]
[2021-10-06 00:00:05,055] {subprocess.py:74} INFO - Output:
[2021-10-06 00:00:05,056] {subprocess.py:78} INFO - ============
[2021-10-06 00:00:05,058] {subprocess.py:78} INFO - 
[2021-10-06 00:00:05,059] {subprocess.py:78} INFO - Not Accurate
[2021-10-06 00:00:05,061] {subprocess.py:78} INFO - 
[2021-10-06 00:00:05,062] {subprocess.py:78} INFO - =============
[2021-10-06 00:00:05,064] {subprocess.py:82} INFO - Command exited with return code 0
[2021-10-06 00:00:05,106] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Not_Accurate, execution_date=20211005T000000, start_date=20211006T000004, end_date=20211006T000005
[2021-10-06 00:00:05,149] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-06 00:00:05,198] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
