[2021-10-17 02:46:42,243] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Not_Accurate 2021-10-16T00:00:00+00:00 [queued]>
[2021-10-17 02:46:42,289] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Not_Accurate 2021-10-16T00:00:00+00:00 [queued]>
[2021-10-17 02:46:42,295] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-17 02:46:42,298] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-17 02:46:42,301] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-17 02:46:42,373] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): Not_Accurate> on 2021-10-16T00:00:00+00:00
[2021-10-17 02:46:42,401] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Not_Accurate', '2021-10-16T00:00:00+00:00', '--job-id', '208', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpl5mgsr4i', '--error-file', '/tmp/tmpmh05ymce']
[2021-10-17 02:46:42,409] {standard_task_runner.py:77} INFO - Job 208: Subtask Not_Accurate
[2021-10-17 02:46:42,387] {standard_task_runner.py:52} INFO - Started process 57111 to run task
[2021-10-17 02:46:42,558] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Not_Accurate 2021-10-16T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-17 02:46:42,778] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Not_Accurate
AIRFLOW_CTX_EXECUTION_DATE=2021-10-16T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-16T00:00:00+00:00
[2021-10-17 02:46:42,782] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-10-17 02:46:42,796] {subprocess.py:63} INFO - Running command: ['bash', '-c', "printf '============\n\nNot Accurate\n\n=============' "]
[2021-10-17 02:46:42,860] {subprocess.py:74} INFO - Output:
[2021-10-17 02:46:42,961] {subprocess.py:78} INFO - ============
[2021-10-17 02:46:42,964] {subprocess.py:78} INFO - 
[2021-10-17 02:46:42,965] {subprocess.py:78} INFO - Not Accurate
[2021-10-17 02:46:42,967] {subprocess.py:78} INFO - 
[2021-10-17 02:46:42,969] {subprocess.py:78} INFO - =============
[2021-10-17 02:46:42,972] {subprocess.py:82} INFO - Command exited with return code 0
[2021-10-17 02:46:43,114] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Not_Accurate, execution_date=20211016T000000, start_date=20211017T024642, end_date=20211017T024643
[2021-10-17 02:46:43,209] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-17 02:46:43,268] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
