[2021-10-22 00:00:05,131] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Not_Accurate 2021-10-21T00:00:00+00:00 [queued]>
[2021-10-22 00:00:05,174] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Not_Accurate 2021-10-21T00:00:00+00:00 [queued]>
[2021-10-22 00:00:05,176] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-22 00:00:05,179] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-22 00:00:05,181] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-22 00:00:05,207] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): Not_Accurate> on 2021-10-21T00:00:00+00:00
[2021-10-22 00:00:05,224] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Not_Accurate', '2021-10-21T00:00:00+00:00', '--job-id', '233', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpqygs_3ix', '--error-file', '/tmp/tmp1js8wl3m']
[2021-10-22 00:00:05,226] {standard_task_runner.py:77} INFO - Job 233: Subtask Not_Accurate
[2021-10-22 00:00:05,213] {standard_task_runner.py:52} INFO - Started process 24792 to run task
[2021-10-22 00:00:05,341] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Not_Accurate 2021-10-21T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-22 00:00:05,436] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Not_Accurate
AIRFLOW_CTX_EXECUTION_DATE=2021-10-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-21T00:00:00+00:00
[2021-10-22 00:00:05,439] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-10-22 00:00:05,441] {subprocess.py:63} INFO - Running command: ['bash', '-c', "printf '============\n\nNot Accurate\n\n=============' "]
[2021-10-22 00:00:05,474] {subprocess.py:74} INFO - Output:
[2021-10-22 00:00:05,495] {subprocess.py:78} INFO - ============
[2021-10-22 00:00:05,497] {subprocess.py:78} INFO - 
[2021-10-22 00:00:05,498] {subprocess.py:78} INFO - Not Accurate
[2021-10-22 00:00:05,499] {subprocess.py:78} INFO - 
[2021-10-22 00:00:05,501] {subprocess.py:78} INFO - =============
[2021-10-22 00:00:05,503] {subprocess.py:82} INFO - Command exited with return code 0
[2021-10-22 00:00:05,551] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Not_Accurate, execution_date=20211021T000000, start_date=20211022T000005, end_date=20211022T000005
[2021-10-22 00:00:05,616] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-22 00:00:05,678] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
