[2021-10-13 00:43:34,104] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Not_Accurate 2021-10-12T00:00:00+00:00 [queued]>
[2021-10-13 00:43:34,139] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Not_Accurate 2021-10-12T00:00:00+00:00 [queued]>
[2021-10-13 00:43:34,141] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 00:43:34,142] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-13 00:43:34,144] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 00:43:34,162] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): Not_Accurate> on 2021-10-12T00:00:00+00:00
[2021-10-13 00:43:34,169] {standard_task_runner.py:52} INFO - Started process 48099 to run task
[2021-10-13 00:43:34,186] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Not_Accurate', '2021-10-12T00:00:00+00:00', '--job-id', '187', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpx2hto9kr', '--error-file', '/tmp/tmprp9nveq9']
[2021-10-13 00:43:34,188] {standard_task_runner.py:77} INFO - Job 187: Subtask Not_Accurate
[2021-10-13 00:43:34,275] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Not_Accurate 2021-10-12T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-13 00:43:34,420] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Not_Accurate
AIRFLOW_CTX_EXECUTION_DATE=2021-10-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-12T00:00:00+00:00
[2021-10-13 00:43:34,429] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-10-13 00:43:34,432] {subprocess.py:63} INFO - Running command: ['bash', '-c', "printf '============\n\nNot Accurate\n\n=============' "]
[2021-10-13 00:43:34,462] {subprocess.py:74} INFO - Output:
[2021-10-13 00:43:34,487] {subprocess.py:78} INFO - ============
[2021-10-13 00:43:34,488] {subprocess.py:78} INFO - 
[2021-10-13 00:43:34,490] {subprocess.py:78} INFO - Not Accurate
[2021-10-13 00:43:34,491] {subprocess.py:78} INFO - 
[2021-10-13 00:43:34,493] {subprocess.py:78} INFO - =============
[2021-10-13 00:43:34,494] {subprocess.py:82} INFO - Command exited with return code 0
[2021-10-13 00:43:34,551] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Not_Accurate, execution_date=20211012T000000, start_date=20211013T004334, end_date=20211013T004334
[2021-10-13 00:43:34,640] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-13 00:43:34,700] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
