[2021-10-18 01:48:05,936] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_A 2021-10-17T00:00:00+00:00 [queued]>
[2021-10-18 01:48:08,345] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_A 2021-10-17T00:00:00+00:00 [queued]>
[2021-10-18 01:48:08,790] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-18 01:48:09,146] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-18 01:48:09,332] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-18 01:48:09,799] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): Training_Model_A> on 2021-10-17T00:00:00+00:00
[2021-10-18 01:48:09,873] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Training_Model_A', '2021-10-17T00:00:00+00:00', '--job-id', '211', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpk82p_f_l', '--error-file', '/tmp/tmptjqippxo']
[2021-10-18 01:48:09,876] {standard_task_runner.py:77} INFO - Job 211: Subtask Training_Model_A
[2021-10-18 01:48:09,849] {standard_task_runner.py:52} INFO - Started process 88748 to run task
[2021-10-18 02:07:32,594] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Training_Model_A 2021-10-17T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-18 02:07:33,655] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Training_Model_A
AIRFLOW_CTX_EXECUTION_DATE=2021-10-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-17T00:00:00+00:00
[2021-10-18 02:07:33,888] {python.py:151} INFO - Done. Returned value was: None
[2021-10-18 02:07:33,945] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Training_Model_A, execution_date=20211017T000000, start_date=20211018T014806, end_date=20211018T020733
[2021-10-18 02:07:34,104] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-18 02:07:34,275] {local_task_job.py:261} INFO - 1 downstream tasks scheduled from follow-on schedule check
